export const loginFields = [
  {
    // labelText: 'Email address',
    // labelFor: 'email-address',
    // id: 'email',
    // autoComplete: 'email',
    value: '',
    name: 'email',
    type: 'email',
    isRequired: true,
    placeholder: 'Email address',
  },
  {
    // labelText: 'Password',
    // labelFor: 'password',
    // id: 'password',
    // autoComplete: 'current-password',
    value: '',
    name: 'password',
    type: 'password',
    isRequired: true,
    placeholder: 'Password',
  },
];

export const signupFields = [
  {
    // labelText: 'Username',
    // labelFor: 'username',
    // autoComplete: 'username',
    // id: 'username',
    value: '',
    name: 'username',
    type: 'text',
    isRequired: true,
    placeholder: 'Username',
  },
  {
    // labelText: 'Email address',
    // labelFor: 'email-address',
    // id: 'email-address',
    // autoComplete: 'email',
    value: '',
    name: 'email',
    type: 'email',
    isRequired: true,
    placeholder: 'Email address',
  },
  {
    // labelText: 'Password',
    // labelFor: 'password',
    // id: 'password',
    // autoComplete: 'current-password',
    value: '',
    name: 'password',
    type: 'password',
    isRequired: true,
    placeholder: 'Password',
  },
  {
    // labelText: 'Confirm Password',
    // labelFor: 'confirm-password',
    // id: 'confirm-password',
    // autoComplete: 'confirm-password',
    name: 'confirm_password',
    value: '',
    type: 'password',
    isRequired: true,
    placeholder: 'Confirm Password',
  },
];
